/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iandtop_common_driver_iccardreader_ReaderJNI */

#ifndef _Included_com_iandtop_common_driver_iccardreader_ReaderJNI
#define _Included_com_iandtop_common_driver_iccardreader_ReaderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iandtop_common_driver_iccardreader_ReaderJNI
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iandtop_common_driver_iccardreader_ReaderJNI_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_iandtop_common_driver_iccardreader_ReaderJNI
 * Method:    openReader
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iandtop_common_driver_iccardreader_ReaderJNI_openReader
  (JNIEnv *, jclass);

/*
 * Class:     com_iandtop_common_driver_iccardreader_ReaderJNI
 * Method:    closeReader
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iandtop_common_driver_iccardreader_ReaderJNI_closeReader
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_iandtop_common_driver_iccardreader_ReaderJNI
 * Method:    requestCard
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iandtop_common_driver_iccardreader_ReaderJNI_requestCard
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_iandtop_common_driver_iccardreader_ReaderJNI
 * Method:    hidLed
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_iandtop_common_driver_iccardreader_ReaderJNI_hidLed
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_iandtop_common_driver_iccardreader_ReaderJNI
 * Method:    hidBeep
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_iandtop_common_driver_iccardreader_ReaderJNI_hidBeep
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_iandtop_common_driver_iccardreader_ReaderJNI
 * Method:    requestCardEx
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_iandtop_common_driver_iccardreader_ReaderJNI_requestCardEx
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_iandtop_common_driver_iccardreader_ReaderJNI
 * Method:    M1ReadData
 * Signature: (IIILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_com_iandtop_common_driver_iccardreader_ReaderJNI_M1ReadData
  (JNIEnv *, jclass, jint, jbyte, jint, jbyteArray);

/*
 * Class:     com_iandtop_common_driver_iccardreader_ReaderJNI
 * Method:    M1WriteData
 * Signature: (IILjava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iandtop_common_driver_iccardreader_ReaderJNI_M1WriteData
  (JNIEnv *, jclass, jint, jbyte, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
